### ISSUE TITLE
invalid use of PropTypes.oneOf

### ISSUE THREAD

**Issue by DocCaliban** [pckhoi/react-flop-card#3]
in the rotate-card.js you have the following lines:
  width: PropTypes.oneOf(PropTypes.number, PropTypes.string),
  height: PropTypes.oneOf(PropTypes.number, PropTypes.string),

They are wrong, it should be an array like so:
  width: PropTypes.oneOfType([PropTypes.number, PropTypes.string]),
  height: PropTypes.oneOfType([PropTypes.number, PropTypes.string]),

Great component otherwise

**Comment by DocCaliban** [comment]
Created a pull request to address this issue

**Comment by pckhoi** [comment]
Thanks! I will investigate further and bump up version to 0.3.1 if it's possible to apply this bug fix.
