### ISSUE TITLE
Unintended back display on Safari

### ISSUE THREAD

**Issue by slassen** [pckhoi/react-flop-card#5]
On Safari and Safari Mobile when it should be showing the back of the card it shows the writing of the front card backwards. It doesn't show the back card at all.

**Comment by pckhoi** [comment]
Thanks for reporting! I'm going to publish a new version that will fix this. Once I do please let me know if it fix the issue and what's the version of your Safari.

**Comment by pckhoi** [comment]
@slassen please give v0.3.2 a try and let me know the result.

**Comment by slassen** [comment]
Thanks for making it. It’s an awesome package.

iOS v11.2.2 for Safari Mobile
v11.0.2 for Safari on MacOS High Sierra

The updated product works! Thanks!
